import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'

import { AiOutlineMenu, AiOutlineClose } from 'react-icons/ai'
import guruji from '../../public/guruji.jpg'
import rekha_main from '../../public/rekha_main.jpg'

export default function Home() {
  const [hamburger, sethamburger] = useState(true)

  return (
    <>
      <Head>
        <title>Mrs Rekha Arora</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className=' bg-[#510000] w-[100vw] h-[142vh]'>
        <div className='absolute top-24 left-7 h-[48vw] w-[48vw] aspect-square '>
        <Image src={rekha_main} alt='rekha_main' fill={true} className="object-cover rounded-full" />
        </div>
        <div className='absolute top-7 right-7 h-[48vw] w-[48vw]0 aspect-square '>
        <Image src={guruji} alt='Guruji' fill={true} className="object-cover rounded-full" />
        </div>

      <div className='absolute top-72 w-full'>
        <h1 className='heading text-5xl text-[3.4rem] text-center font-bold font-molengo'>Rekha Arora</h1>
        <h3 className='heading text-3xl text-center font-kanit pt-2'>1943-2023</h3>
        <h4 className='text-white text-4xl  text-center font-tangerine pt-6'>Within the profound memory of hers</h4>
        <p className='text-white text-base px-5 text-justify pb-5 pt-3 '>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus sint rem unde nam optio consequatur voluptate accusantium labore recusandae impedit ratione molestiae quos iure pariatur nisi, culpa quaerat assumenda nihil modi doloremque. Voluptate nam nobis, doloribus adipisci, incidunt ab accusantium dolor ratione magnam voluptatum recusandae doloremque, voluptates nihil distinctio sequi.</p>


        <div className='flex space-y-5 pb-5 flex-col'>
          {/* Check out: */}
          <div className='heading text-center  text-2xl  p-2 w-[90%] mx-auto border-2 border-red-200 rounded-lg '>My Journey</div>
          <div className='heading text-center  text-2xl  p-2 w-[90%] mx-auto border-2 border-red-200 rounded-lg '>My Family and Friends</div>
          <div className='heading text-center  text-2xl  p-2 w-[90%] mx-auto border-2 border-red-200 rounded-lg '>Photo Album</div>
        </div>

        <div className='w-full h-32 bg-green-500'>dsf</div>

        </div>
      </div>

<div className='fixed  bottom-0 left-0 h-32 w-[100vw] bg-[#510000] shadowOnImg'>
  <Image src="/set.png" alt='set' fill={true} className=" scale-90 " />
</div>

     

    </>
  )
}
