import Head from "next/head";
import Image from "next/image";
import { useState,useRef,useLayoutEffect ,useEffect} from "react";


import { AiOutlineMenu, AiOutlineClose } from "react-icons/ai";
import guruji from "../../public/guruji.jpg";
import rekha_main from "../../public/rekha_main.jpg";
import scroll from "../../public/scroll.png";

export default function Home() {

  

  return (
    <div className="bg-[#510000] ">
      <Head>
        <title>Mrs Rekha Arora</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>


      {/* main content div  */}
      <div className=" bg-[#510000] w-full h-full xl:h-[80vh] lg:flex lg:px-20">
        <div className="md:scale-75 lg:w-[30%] lg:scale-100 lg:flex lg:flex-col lg:space-y-7 lg:ml-5 lg:justify-center lg:h-[100vh] xl:w-[50%]">
          <div className="absolute lg:relative top-24 left-7 h-[48vw] w-[48vw] lg:h-auto lg:w-full lg:top-0 lg:left-0 aspect-square   xl:w-[48%] xl:left-10 xl:top-10">
            <Image
              src={rekha_main}
              alt="rekha_main"
              fill={true}
              className="object-cover rounded-full lg:border-[5px] lg:border-yellow-700"
            />
          </div>
          <div className="absolute top-7 lg:relative right-7 h-[48vw] w-[48vw] lg:top-0 lg:left-0 lg:h-auto lg:w-full  aspect-square xl:absolute xl:top-[calc(50%-17rem)] xl:left-80 xl:w-[48%]">
            <Image
              src={guruji}
              alt="Guruji"
              fill={true}
              className="object-cover rounded-full lg:border-[5px] lg:border-yellow-700"
            />
          </div>
        </div>

        <div className="absolute top-[19rem] lg:static md:top-[calc(50vw-40px)]  lg:flex lg:flex-col lg:justify-center w-full md:text-xl md:w-[calc(100%-160px)] md:left-[80px] xl:w-[50%] xl:h-[100vh] xl:pr-7">
          <h1 className=" text-4xl text-center font-bold font-molengo xl:text-7xl">
         <span className="heading">Join me on a journey</span> <span className="heading">through my memories.</span>
          </h1>
          {/* <h3 className="heading text-3xl text-center font-kanit pt-2 xl:text-4xl">
            1943-2023
          </h3> */}
          <h4 className="text-white text-4xl  text-center font-tangerine pt-6 xl:text-5xl">
            Within the profound memory of hers
          </h4>
          <p className="text-white text-base px-5 text-center pb-5 pt-3 xl:text-xl ">
          I am a person of strength and determination. As a teacher, I approach my students with firmness and compassion, guiding them towards their full potential. My love for my home state of Punjab drives me to make a positive impact on the lives of others.  I strive to leave a lasting legacy, inspiring others to carry on my work even after I am gone.
          </p>

          {/* <div className='grid space-y-5 xl:hidden pb-5 lg:grid-cols-2 lg:px-6 lg:gap-x-6'>
      
          <div className='heading text-center  text-2xl  p-2 w-[90%] lg:w-full mx-auto border-2 border-red-200 lg:border-yellow-600 lg:font-semibold rounded-lg lg:col-span-2'>My Family and Friends</div>
          <div className='heading text-center  text-2xl  p-2 w-[90%] lg:w-full mx-auto border-2 border-red-200 lg:border-yellow-600 lg:font-semibold rounded-lg '>My Journey</div>
          <div className='heading text-center  text-2xl  p-2 w-[90%] lg:w-full mx-auto border-2 border-red-200 lg:border-yellow-600 lg:font-semibold rounded-lg '>Photo Album</div>
        </div> */}

          <div className="w-full h-32 sm:hidden bg-transparent"></div>
        </div>
      </div>

      {/* bottom image on phone  */}
      <div className="fixed sm:hidden bottom-0 left-0 h-32 w-[100vw] bg-[#510000] shadowOnImg">
        <Image src="/set.png" alt="set" fill={true} className=" scale-90 " />
      </div>

      {/* left image on md+  */}
      <div className="fixed hidden sm:block rotate-90 top-[calc(50%-40px)] right-[calc(50%-40px)] h-20 w-full  ">
        <Image
          src="/set.png"
          alt="set"
          fill={true}
          className=" scale-90 object-contain"
        />
      </div>

      {/* right img on md+  */}
      <div className="fixed hidden sm:block -rotate-90 top-[calc(50%-40px)] left-[calc(50%-40px)] h-20 w-full  ">
        <Image
          src="/set.png"
          alt="set"
          fill={true}
          className=" scale-90 object-contain"
        />
      </div>

     
    </div>
  );
}
